### ISSUE TITLE
Error in fam.fn() : Only 1<p<=2 supported

### ISSUE THREAD

**Issue by Hanqingpeng** [gordy2x/saint#5]
manyany("glm",spe,data=X,spe~1,family="Tweedie",var.power=1)
Error in fam.fn() : Only 1<p<=2 supported

**Comment by gordy2x** [comment]
Hi @Hanqingpeng, thanks for the message. manyany is actually a function in the mvabund package, so I don't have control over the code there. In addition in ecology we usually use the tweedie with 1<p<=2 as in this range is has a point mass at 0 as well as a continuous component, I would think that is why this range is imposed.
